version: "3"

services:
  docs:
    container_name: kubernetes_docs
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/code/